#ifndef JSON_TYPES_
#define JSON_TYPES_

enum JSONType {
    JSON_TYPE_CHAR,
    JSON_TYPE_STRING,
    JSON_TYPE_INTEGER,
    JSON_TYPE_LONG,
    JSON_TYPE_DOUBLE,
    JSON_TYPE_OBJECT,
    JSON_TYPE_ARRAY,
    JSON_TYPE_NAT, // NOT A TYPE
    JSON_TYPE_TYPE_COUNT
};

#endif // JSON_TYPES_

